### ISSUE TITLE
New Pic 

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#22]
Hopefully the logo fits in the center! I think I'd like the color one, but the B&W might look better. I can re-arrange and re-take pic if this doesn't work in terms of the open space in the center as I don't like the pixels you can see around my logo on the current pic. The current pic behind the logo I would like to use in color in the about section as that is the back of my biz card and the image on the sign that I use at shows. Thanks! 

![img_3908 1](https://cloud.githubusercontent.com/assets/20828528/18401547/019db44a-76a9-11e6-8904-cb9db449543a.jpg)
![img_3908](https://cloud.githubusercontent.com/assets/20828528/18401548/019f8e3c-76a9-11e6-97c7-e399195eda20.jpg)

**Comment by denniswhitney2000** [comment]
These I can work with! 
Nice photos btw!

**Comment by denniswhitney2000** [comment]
ok, in place. Which do you like better?
![homepage2](https://cloud.githubusercontent.com/assets/13984926/18412555/8f349c9a-775f-11e6-825f-c1986cebd56d.jpg)
![homepage1](https://cloud.githubusercontent.com/assets/13984926/18412554/8f31c38a-775f-11e6-8d27-5d10fe5b565b.jpg)

**Comment by zinniadesignsTC** [comment]
Hummm I don't know! I might have to take a vote and get back to you. I'll redo the picture as the layout isn't quite right for the logo...need to add a few dishes to the left side of the logo. 

Zinnia Designs
Custom Ceramics & More
By Tanya Chin
www.zinnia-designs.com

**Comment by denniswhitney2000** [comment]
Before you go nuts, I need to recut that photo anyway.  Give me a day or 2, ok?

Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone
-------- Original message --------From: zinniadesignsTC notifications@github.com Date: 9/10/16  5:02 PM  (GMT-05:00) To: denniswhitney2000/ZinniaCeramics ZinniaCeramics@noreply.github.com Cc: denniswhitney2000 denniswhitney2000@yahoo.com, Comment comment@noreply.github.com Subject: Re: [denniswhitney2000/ZinniaCeramics] New Pic (#22) 
Hummm I don't know! I might have to take a vote and get back to you. I'll redo the picture as the layout isn't quite right for the logo...need to add a few dishes to the left side of the logo. 

Zinnia Designs

Custom Ceramics & More

By Tanya Chin

www.zinnia-designs.com

> On Sep 10, 2016, at 2:05 PM, denniswhitney2000 notifications@github.com wrote:
> 
> ok, in place. Which do you like better?
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/denniswhitney2000/ZinniaCeramics","title":"denniswhitney2000/ZinniaCeramics","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/denniswhitney2000/ZinniaCeramics"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zinniadesignsTC in #22: Hummm I don't know! I might have to take a vote and get back to you. I'll redo the picture as the layout isn't quite right for the logo...need to add a few dishes to the left side of the logo. \n\nZinnia Designs\nCustom Ceramics \u0026 More\nBy Tanya Chin\nwww.zinnia-designs.com\n\n\n\u003e On Sep 10, 2016, at 2:05 PM, denniswhitney2000 \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e ok, in place. Which do you like better?\n\u003e \n\u003e \n\u003e \n\u003e —\n\u003e You are receiving this because you authored the thread.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/denniswhitney2000/ZinniaCeramics/issues/22#issuecomment-246140181"}}}

**Comment by zinniadesignsTC** [comment]
I kept the dishes as is on a board so I just need to add a dish or 2 - totally easy on my end. 

Zinnia Designs
Custom Ceramics & More
By Tanya Chin
www.zinnia-designs.com

**Comment by zinniadesignsTC** [comment]
ok so vote is in- color! 
zinnia designsCustom Ceramics, Accessories & More
by Tanya Chin
781/449/0263
www.zinnia-designs.com
Etsy Online Shop

Connect with me on Facebookhttp://www.facebook.com/zinniadesigns

```
  From: denniswhitney2000 <notifications@github.com>
```

 To: denniswhitney2000/ZinniaCeramics ZinniaCeramics@noreply.github.com 
Cc: zinniadesignsTC tanyaphilbin@yahoo.com; Author author@noreply.github.com
 Sent: Sunday, September 11, 2016 12:45 AM
 Subject: Re: [denniswhitney2000/ZinniaCeramics] New Pic (#22)

Before you go nuts, I need to recut that photo anyway.  Give me a day or 2, ok?

Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone
-------- Original message --------From: zinniadesignsTC notifications@github.com Date: 9/10/16 5:02 PM (GMT-05:00) To: denniswhitney2000/ZinniaCeramics ZinniaCeramics@noreply.github.com Cc: denniswhitney2000 denniswhitney2000@yahoo.com, Comment comment@noreply.github.com Subject: Re: [denniswhitney2000/ZinniaCeramics] New Pic (#22) 
Hummm I don't know! I might have to take a vote and get back to you. I'll redo the picture as the layout isn't quite right for the logo...need to add a few dishes to the left side of the logo. 

Zinnia Designs

Custom Ceramics & More

By Tanya Chin

www.zinnia-designs.com

> On Sep 10, 2016, at 2:05 PM, denniswhitney2000 notifications@github.com wrote:
> 
> ok, in place. Which do you like better?
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/denniswhitney2000/ZinniaCeramics","title":"denniswhitney2000/ZinniaCeramics","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/denniswhitney2000/ZinniaCeramics"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zinniadesignsTC in #22: Hummm I don't know! I might have to take a vote and get back to you. I'll redo the picture as the layout isn't quite right for the logo...need to add a few dishes to the left side of the logo. \n\nZinnia Designs\nCustom Ceramics \u0026 More\nBy Tanya Chin\nwww.zinnia-designs.com\n\n\n\u003e On Sep 10, 2016, at 2:05 PM, denniswhitney2000 \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e ok, in place. Which do you like better?\n\u003e \n\u003e \n\u003e \n\u003e —\n\u003e You are receiving this because you authored the thread.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/denniswhitney2000/ZinniaCeramics/issues/22#issuecomment-246140181"}}}—

**Comment by zinniadesignsTC** [comment]
Here's the updated pic
![img_3912 1](https://cloud.githubusercontent.com/assets/20828528/18497390/d1b73dea-79fb-11e6-8696-1379cf72167c.jpg)

**Comment by denniswhitney2000** [comment]
this is in place on my dev, but not yet deployed...
